# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7c6da2778891d0b145c7329ccf3b5a4fe1ba74f4eda76afcd7df4d98263fd96ce7e98cb21a3af0b99c60089b29a5ba8e6e0be24aa2268c5b3809c48fb0299a0

test:
  secret_key_base: 4db18bba3fd97b4aaeed4c8e8f59042598d337c325ebf6ff6b06996b8bc34f48a76ec09de27680da10452ceb005816d4c43d7b8f5d7ac1f9d364158d776c7fe5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
